plugins:
  - jekyll-relative-links
  - jekyll-remote-theme 
  
relative_links:
  enabled: true
  collections: false
  
include:
  - _config.yml
  - README.md
  - LICENSE.md

markdown: GFM
show_downloads: false
remote_theme: cotes2020/jekyll-theme-chirpy
#theme:  jekyll-theme-architect
title: "Before you prompt"


