plugins:
  - jekyll-relative-links
  
relative_links:
  enabled: true
  collections: false
  
include:
  - _config.yml
  - README.md
  - LICENSE.md

markdown: GFM
show_downloads: false
theme:  jekyll-theme-architect
title: "Before you prompt"

#remote_theme: cotes2020/jekyll-theme-chirpy

